import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import { montserrat } from "./fonts/fonts";
import "./globals.css";
import Navbar from './ui/navbar'
import Footer from './ui/footer'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${montserrat.className} antialiased`}
        >
          <AuthProvider>
            <div className="min-h-screen flex flex-col">
              <Navbar/>
              <div className="flex flex-grow flex-col">
                {children}
              </div>
              <Footer/>
            </div>
          </AuthProvider>
        </body>
    </html>
  );
}
